name: Build and deploy container app to Azure Web App - yt-down-be

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://ytdown.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_d326957d10fe41359d36c4ffb398247c }}
          password: ${{ secrets.AzureAppService_ContainerPassword_56b811b20d844a31bdbb63f4c676d726 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ytdown.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d326957d10fe41359d36c4ffb398247c }}/yt-down-be:${{ github.sha }}
          file: ./server/Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'yt-down-be'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_bfd90b4d196e4565a1ba2a3f86e7b1eb }}
            images: 'ytdown.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d326957d10fe41359d36c4ffb398247c }}/yt-down-be:${{ github.sha }}'