# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - yt-down-be

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ytdown.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_89c28a3dfd34403591931a7bdd20af62 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_407c81ecc66a4ef7bf54eb7d9a2d4770 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ytdown.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_89c28a3dfd34403591931a7bdd20af62 }}/yt-down-be:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'yt-down-be'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_55e1550fce614ca48b087ae16feb8219 }}
        images: 'ytdown.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_89c28a3dfd34403591931a7bdd20af62 }}/yt-down-be:${{ github.sha }}'