name: Server CD

on:
    push:
      branches: [ main ]
      paths:
        - 'server/**'
  
    pull_request:
      branches: [ main ]
      paths:
        - 'server/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
